void resetArray(char input[], int size);
void toLowerCase(char str[]);
void getNumVertices(FILE **fp, int *numVertices);
void sortNeighbors(char neighbors[][MAX_NAMELENGTH], int neighborTotal);
void swapSequenceType(SequenceType *a, SequenceType *b);
void sortVertices(SequenceType vertices[], int numVertices);
void readInput(FILE **fp, SequenceType vertices[], int numVertices);
int isValidName(SequenceType vertices[], int numVertices, char inputName[]);
int startIndex(SequenceType vertices[], int numVertices);
void printGraph(SequenceType vertices[], int numVertices);
void createAdjMatrix(SequenceType vertices[], int numVertices);
int longestString(SequenceType vertices[], int numVertices);
int print(SequenceType vertices[], int numVertives);
void printVertexDegrees(FILE **fp, SequenceType vertices[], int numVertices);